spring:
  datasource:
    driverClassName: org.h2.Driver
    sql:
      init:
        mode: always
    url: jdbc:h2:mem:alura-forum-test
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
